<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <EnableHarmony>true</EnableHarmony>
    <EnableModDeploy>true</EnableModDeploy>
    <EnableModZip>true</EnableModZip>
    <ModFolderName>CloudSync</ModFolderName>
    <GamePath Condition="!Exists('$(GamePath)')">C:\Games\Stardew Valley\game</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
